export const consultations = [
    {
        "since": "08:00",
        "until": "21:00",
        "pay_method": ["Obra social", "Transferencia"],
        "days": ["Lunes", "Miércoles"],
        "mode": "Virtual",
        "cost": "1500",
        "duration": "30 minutos",
        "fk_id_doctor": "1",
        "id_doctor_consultation_data": "1",
        "socialWork": ["OSDE"],
        "transferData": {},
        "cash": "No",
        "speciality": ["Niños", "Adolescentes"]
    },
    {
        "since": "09:00",
        "until": "18:00",
        "pay_method": ["Efectivo", "Transferencia"],
        "days": ["Martes", "Jueves"],
        "mode": "Presencial",
        "cost": "1000",
        "duration": "30 minutos",
        "fk_id_doctor": "1",
        "id_doctor_consultation_data": "1",
        "socialWork": ["OSDE"],
        "transferData": {},
        "cash": "No",
        "speciality": ["Niños", "Adolescentes"]
    },
    {
        "since": "09:00",
        "until": "18:00",
        "pay_method": ["Efectivo", "Transferencia"],
        "days": ["Martes", "Jueves"],
        "mode": "Virtual",
        "cost": "1500",
        "duration": "45 minutos",
        "fk_id_doctor": "2",
        "id_doctor_consultation_data": "2",
        "socialWork": ["Swiss Medical"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Adultos", "Mayores"]
    },
    {
        "since": "10:00",
        "until": "19:00",
        "pay_method": ["Obra social"],
        "days": ["Lunes", "Viernes"],
        "mode": "Virtual",
        "cost": "1200",
        "duration": "60 minutos",
        "fk_id_doctor": "3",
        "id_doctor_consultation_data": "3",
        "socialWork": ["Galeno"],
        "transferData": {},
        "cash": "No",
        "speciality": ["Neonatología", "Niños"]
    },
    {
        "since": "07:00",
        "until": "16:00",
        "pay_method": ["Efectivo"],
        "days": ["Martes", "Jueves"],
        "mode": "Presencial",
        "cost": "800",
        "duration": "30 minutos",
        "fk_id_doctor": "4",
        "id_doctor_consultation_data": "4",
        "socialWork": ["Medicard"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Adultos"]
    },
    {
        "since": "11:00",
        "until": "20:00",
        "pay_method": ["Transferencia"],
        "days": ["Miércoles", "Viernes"],
        "mode": "Virtual",
        "cost": "1100",
        "duration": "45 minutos",
        "fk_id_doctor": "5",
        "id_doctor_consultation_data": "5",
        "socialWork": ["Medicus"],
        "transferData": {},
        "cash": "No",
        "speciality": ["Adolescentes", "Niños"]
    },
    {
        "since": "08:30",
        "until": "17:30",
        "pay_method": ["Efectivo", "Obra social"],
        "days": ["Lunes", "Miércoles", "Viernes"],
        "mode": "Presencial",
        "cost": "1300",
        "duration": "30 minutos",
        "fk_id_doctor": "6",
        "id_doctor_consultation_data": "6",
        "socialWork": ["OSDE", "Swiss Medical"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Adultos", "Mayores"]
    },
    {
        "since": "09:30",
        "until": "18:30",
        "pay_method": ["Obra social", "Transferencia"],
        "days": ["Martes", "Jueves"],
        "mode": "Virtual",
        "cost": "1400",
        "duration": "60 minutos",
        "fk_id_doctor": "7",
        "id_doctor_consultation_data": "7",
        "socialWork": ["Galeno", "Medicus"],
        "transferData": {},
        "cash": "No",
        "speciality": ["Niños", "Adolescentes"]
    },
    {
        "since": "10:00",
        "until": "19:00",
        "pay_method": ["Efectivo"],
        "days": ["Lunes", "Miércoles"],
        "mode": "Presencial",
        "cost": "900",
        "duration": "45 minutos",
        "fk_id_doctor": "8",
        "id_doctor_consultation_data": "8",
        "socialWork": ["OSDE"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Mayores"]
    },
    {
        "since": "11:30",
        "until": "20:30",
        "pay_method": ["Obra social", "Transferencia"],
        "days": ["Martes", "Jueves"],
        "mode": "Virtual",
        "cost": "1250",
        "duration": "30 minutos",
        "fk_id_doctor": "9",
        "id_doctor_consultation_data": "9",
        "socialWork": ["Swiss Medical", "Galeno"],
        "transferData": {},
        "cash": "No",
        "speciality": ["Neonatología"]
    },
    {
        "since": "07:30",
        "until": "16:30",
        "pay_method": ["Efectivo", "Transferencia"],
        "days": ["Lunes", "Viernes"],
        "mode": "Presencial",
        "cost": "1100",
        "duration": "60 minutos",
        "fk_id_doctor": "10",
        "id_doctor_consultation_data": "10",
        "socialWork": ["Medicard"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Adultos", "Niños"]
    },
    {
        "since": "07:30",
        "until": "16:30",
        "pay_method": ["Efectivo", "Transferencia"],
        "days": ["Lunes", "Viernes"],
        "mode": "Presencial",
        "cost": "1100",
        "duration": "60 minutos",
        "fk_id_doctor": "11",
        "id_doctor_consultation_data": "10",
        "socialWork": ["Medicard"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Adultos", "Niños"]
    },
    {
        "since": "07:30",
        "until": "16:30",
        "pay_method": ["Efectivo", "Transferencia"],
        "days": ["Lunes", "Viernes"],
        "mode": "Presencial",
        "cost": "1100",
        "duration": "60 minutos",
        "fk_id_doctor": "12",
        "id_doctor_consultation_data": "10",
        "socialWork": ["Medicard"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Adultos", "Niños"]
    },
    {
        "since": "07:30",
        "until": "16:30",
        "pay_method": ["Efectivo", "Transferencia"],
        "days": ["Lunes", "Viernes"],
        "mode": "Virtual",
        "cost": "1100",
        "duration": "60 minutos",
        "fk_id_doctor": "14",
        "id_doctor_consultation_data": "10",
        "socialWork": ["Medicard"],
        "transferData": {},
        "cash": "Sí",
        "speciality": ["Adultos", "Niños"]
    },
];
