export const users = [
    {
        "id_user": 1,
        "name": "Ricardo",
        "lastname": "Calvo",
        "DNI": 23456789,
        "mail": "ricardo.calvo@example.com",
        "birthdate": new Date('1980-01-15'),
        "gender": "Male",
        "username": "ricardocalvo",
        "password": "password123",
        "phone": 123456789,
        "id_country": 1,
        "id_province": 1,
        "id_department": 1
    },
    {
        "id_user": 2,
        "name": "María",
        "lastname": "González",
        "DNI": 34567890,
        "mail": "maria.gonzalez@example.com",
        "birthdate": new Date('1985-05-20'),
        "gender": "Female",
        "username": "mariagonzalez",
        "password": "password123",
        "phone": 234567890,
        "id_country": 1,
        "id_province": 2,
        "id_department": 2
    },
    {
        "id_user": 3,
        "name": "Juan",
        "lastname": "Martínez",
        "DNI": 45678901,
        "mail": "juan.martinez@example.com",
        "birthdate": new Date('1990-07-10'),
        "gender": "Male",
        "username": "juanmartinez",
        "password": "password123",
        "phone": 345678901,
        "id_country": 1,
        "id_province": 3,
        "id_department": 3
    },
    {
        "id_user": 4,
        "name": "Ana",
        "lastname": "Pérez",
        "DNI": 56789012,
        "mail": "ana.perez@example.com",
        "birthdate": new Date('1992-08-25'),
        "gender": "Female",
        "username": "anaperez",
        "password": "password123",
        "phone": 456789012,
        "id_country": 1,
        "id_province": 4,
        "id_department": 4
    },
    {
        "id_user": 5,
        "name": "Carlos",
        "lastname": "López",
        "DNI": 67890123,
        "mail": "carlos.lopez@example.com",
        "birthdate": new Date('1988-03-30'),
        "gender": "Male",
        "username": "carloslopez",
        "password": "password123",
        "phone": 567890123,
        "id_country": 1,
        "id_province": 5,
        "id_department": 5
    },
    {
        "id_user": 6,
        "name": "Lucía",
        "lastname": "Ramírez",
        "DNI": 78901234,
        "mail": "lucia.ramirez@example.com",
        "birthdate": new Date('1995-11-11'),
        "gender": "Female",
        "username": "luciaramirez",
        "password": "password123",
        "phone": 678901234,
        "id_country": 1,
        "id_province": 6,
        "id_department": 6
    },
    {
        "id_user": 7,
        "name": "Pedro",
        "lastname": "Fernández",
        "DNI": 89012345,
        "mail": "pedro.fernandez@example.com",
        "birthdate": new Date('1979-02-18'),
        "gender": "Male",
        "username": "pedrofernandez",
        "password": "password123",
        "phone": 789012345,
        "id_country": 1,
        "id_province": 7,
        "id_department": 7
    },
    {
        "id_user": 8,
        "name": "Laura",
        "lastname": "Torres",
        "DNI": 90123456,
        "mail": "laura.torres@example.com",
        "birthdate": new Date('1984-09-05'),
        "gender": "Female",
        "username": "lauratorres",
        "password": "password123",
        "phone": 890123456,
        "id_country": 1,
        "id_province": 8,
        "id_department": 8
    },
    {
        "id_user": 9,
        "name": "Miguel",
        "lastname": "Sánchez",
        "DNI": 11234567,
        "mail": "miguel.sanchez@example.com",
        "birthdate": new Date('1981-04-22'),
        "gender": "Male",
        "username": "miguelsanchez",
        "password": "password123",
        "phone": 901234567,
        "id_country": 1,
        "id_province": 9,
        "id_department": 9
    },
    {
        "id_user": 10,
        "name": "Patricia",
        "lastname": "Moreno",
        "DNI": 12345678,
        "mail": "patricia.moreno@example.com",
        "birthdate": new Date('1993-06-14'),
        "gender": "Female",
        "username": "patriciamoreno",
        "password": "password123",
        "phone": 123456780,
        "id_country": 1,
        "id_province": 10,
        "id_department": 10
    }
];

